[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200
port = 8501

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#3b82f6"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8fafc"
textColor = "#1f2937"
font = "sans serif"

[client]
caching = true
showErrorDetails = true

[runner]
magicEnabled = true
installTracer = true
fixMatplotlib = true

[logger]
level = "info"
